### ISSUE TITLE
Unable to select mod showing "plugin not loaded"

### ISSUE THREAD

**Issue by IceLancerSR** [focustense/easymod#101]
Plugin not loaded. Mod only contains textures and meshes.
I can't select face from that mod. because plugin is missing.
I guess i could create dummy plugin so this tool would accept it?
or there is better way?

**Comment by focustense** [comment]
Yes, you could create a dummy plugin as a short-term workaround.

The mod _should_ still be selectable, even though the plugin is missing. It was just discovered that it isn't, and that's a bug.

To be specific, it actually _does_ select that mod. But (a) it doesn't show the new selection, and (b) doesn't seem to restore the selection properly if you exit and restart.

Giving it a plugin with ITM records will definitely allow it to work normally.

**Comment by IceLancerSR** [comment]
mm 
I created empty plugin with wrye , that didn't work.
then i opened in sssedit and added skyrim and dlc's as masters. Its still not working. 
I have plugin enabled its flagged esl

**Comment by focustense** [comment]
An empty plugin wouldn't do anything at all - the plugin needs to have records for those NPCs. It's the records that matter, not the plugins.

You'd have to copy the NPC records from the master into your dummy plugin. Just leaving them ITM is fine. And make sure the plugin is in the mod directory with the loose facegen files.

**Comment by focustense** [comment]
I haven't looked at the UI side of the issue yet, but as far as failing to restore an override from autosave on subsequent startups, this comes down to two problems.

First, although the `NpcModel` was coded to treat the mod name as a locator key, some code was added to the `ProfileFactory` afterward that does _not_ do this, and instead always tries to treat it as a mod name which doesn't exist. This is why it didn't come up in early testing, because it was loading from older profiles that saved names rather than keys.

Second, it needs to search for the mod in the mod repository, but the loader code doesn't wait for the mod repository to be fully indexed before creating the profile. This was an intentional decision at the time, but overlooked this dependency. Unfortunately it may delay startup by a bit (hopefully not more than a fraction of a second) to force the profile task to wait longer, but it is necessary to guarantee consistency.

Another aspect of this that's not in this particular bug description, but was reported yesterday, is the fact that there must be at least two possible records in order for the NPC to show up in the profile at all. So if there are 2 records, and the FaceGen override presents a 3rd option, then all 3 will show for that NPC... but if there is only one record (i.e. vanilla) plus the loose facegen, the NPC will not show up at all. In order to have these always show up in the profile, these extra facegens must be considered in the initial pass, which is another reason why it is necessary to wait for the mod repo to finish indexing.

I'll look into/comment on the UI issue later, only had a few minutes to look at this right now.

**Comment by IceLancerSR** [comment]
> I haven't looked at the UI side of the issue yet, but as far as failing to restore an override from autosave on subsequent startups, this comes down to two problems.
> 
> First, although the `NpcModel` was coded to treat the mod name as a locator key, some code was added to the `ProfileFactory` afterward that does _not_ do this, and instead always tries to treat it as a mod name which doesn't exist. This is why it didn't come up in early testing, because it was loading from older profiles that saved names rather than keys.
> 
> Second, it needs to search for the mod in the mod repository, but the loader code doesn't wait for the mod repository to be fully indexed before creating the profile. This was an intentional decision at the time, but overlooked this dependency. Unfortunately it may delay startup by a bit (hopefully not more than a fraction of a second) to force the profile task to wait longer, but it is necessary to guarantee consistency.
> 
> Another aspect of this that's not in this particular bug description, but was reported yesterday, is the fact that there must be at least two possible records in order for the NPC to show up in the profile at all. So if there are 2 records, and the FaceGen override presents a 3rd option, then all 3 will show for that NPC... but if there is only one record (i.e. vanilla) plus the loose facegen, the NPC will not show up at all. In order to have these always show up in the profile, these extra facegens must be considered in the initial pass, which is another reason why it is necessary to wait for the mod repo to finish indexing.
> 
> I'll look into/comment on the UI issue later, only had a few minutes to look at this right now.

I think that post belongs to different issue?

**Comment by focustense** [comment]
All part of this issue.
