### ISSUE TITLE
Something went wrong error when starting build.

### ISSUE THREAD

**Issue by kac813** [focustense/easymod#102]
Checked for errors then started the build after a few seconds I get the error message then it closes.
https://pastebin.com/Myy70pH8

**Comment by focustense** [comment]
I opened the original, non-converted plugin in xEdit and can see that `0012D0` does exist. As expected, it's an armor, `AAMSBody`.

So this looks like a bad conversion to me. How was it converted?

**Comment by focustense** [comment]
As of [v0.9.3](https://github.com/focustense/easymod/releases/tag/v0.9.3), there is now a reference checker (#107) which runs on startup and should provide what I hope is very clear guidance on where the errors are. NPC options with invalid references will be disabled in the profile, so they can't be selected and subsequently break the build.

Because this now exists, I'm closing all prior issues related to invalid references. Please report any bugs or other problems you find with the reference checker in a new GitHub issue. Thanks!
