### ISSUE TITLE
Crash after loading profile

### ISSUE THREAD

**Issue by IceLancerSR** [focustense/easymod#103]
Additional text encountered after finished reading JSON content: t. Path '', line 1, position 152
[Log_20210827_192137_3792048.txt](https://github.com/focustense/easymod/files/7068633/Log_20210827_192137_3792048.txt)

I saved npc settings , then reseted everything , loaded profile back and i cant start app now.
If i delete profile, i can start app again , load profile , go to check for error and it crashes again

I opened profile and there are a lot of out of place lines
![ammm](https://user-images.githubusercontent.com/4452102/131167262-15b53864-d74f-47c8-a56a-789ac5b43a40.jpg)

**Comment by focustense** [comment]
For reasons I don't recall anymore, I apparently thought it was a good idea to move the profile load into a parallel loop. This corruption is happening because multiple threads are all trying to append to the file at the same time.

I'll fix this in the next release. In the meantime, there is a workaround that seemed to work for me, albeit a very ugly one.

1. Delete profile.log and start EasyNPC (this is the same as resetting everything, which you already did).
2. Open up Task manager to the Details tab.
3. Right-click on EasyNPC.exe, click "Set affinity", and pick any CPU and **only** that CPU (i.e. ensure that only one is selected), then click OK.
4. Import your previously-exported profile in EasyNPC.
5. Make sure to set EasyNPC **back** to all cores in the task manager afterward, otherwise most parts of the app (especially builds) are going to run very very slow.

This worked for me. By temporarily restricting the app to use a single core, it forces the app to only write one profile entry at a time, which negates the effect of the bug.

**Comment by focustense** [comment]
Since reports are still coming in about this, I'm adding a post here to document the current fix.

1. **Update to version 0.9.3 or later**, otherwise it will just happen again.
2. Open an Explorer window to `%LocalAppData%\EasyNPC` (the EasyNPC data directory).
3. Delete or rename `Profile.log`.
4. Start EasyNPC again. It will create a new `Profile.log`.
5. Import the same saved profile that you tried to import last time.

You _don't_ need the core affinity workaround in v0.9.3 and newer - that was only for v0.9.2.

Also, please note that **even if you are already on v0.9.3 or above**, you may still have this problem if you tried to import a saved profile in v0.9.1 or v0.9.2. As per the steps above, simply upgrading will not fix the corruption problem, you have to delete the corrupted autosave and start a new one.
