### ISSUE TITLE
Program crashes while loading modlist

### ISSUE THREAD

**Issue by Anglo-Saxon-Elf** [focustense/easymod#108]
Launching EasyNPC from MO2. Program crashes while analysing my load order.

https://pastebin.com/MgwS7DhP

**Comment by focustense** [comment]
Looks like you hit #103. I'm guessing you imported a saved profile? Sorry, I completely broke that in 0.9.2, the fix will be in 0.9.3.

Since profile imports are additive, I think you can get the app to start again by opening the profile.log in a text editor and just deleting all the way back to where the corruption starts (it'll be easy to see). Or you can delete profile.log completely, let it build you a new profile, and then import your saved profile again using the core-affinity workaround in #103.

**Comment by focustense** [comment]
Closing as dupe, let me know if you have any issues with the workaround(s).

**Comment by Anglo-Saxon-Elf** [comment]
Yes I imported a profile and then closed the program to check something, then came back to it and hit the crash. I will use your second workaround as I need to look at most of the NPCs again anyway. Thanks for your quick and detailed response.
