### ISSUE TITLE
Corrupted plugins on minimal load order

### ISSUE THREAD

**Issue by Reg1nleifr** [focustense/easymod#110]
I feel like I'm having an issue with the installation/setup of EasyNPC since I couldn't find the issue anywhere so far. Following Setup leads to the following errors. Basically I cannot load any plugins other than the official Skyrim esms because the other Plugins are "corrupted":

**EasyNPC:** 0.9.2.0
**Mod Organizer:** 2.4.2
**Location Easynpc:** F:\Skyrim Wabbajack Profiles\Serenity2latest\tools\EasyNPC\EasyNPC.exe
**Location Mods Folder:** F:\Skyrim Wabbajack Profiles\Serenity2latest\mods
**Skyrim Installation**: F:\Skyrim Wabbajack Profiles\Serenity2latest\Stock Game
**Additional info:** F is not my main drive.

```[EasyNPC] Initialized: EasyNPC version 0.9.2.0, built on 08/27/2021 01:35:03
[EasyNPC] Plugin "Unofficial Skyrim Special Edition Patch.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "PAN_NPCs_Males2.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "PAN_NPCs.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "PAN_NPCs_DG.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "PAN_NPCs_DB.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "Bijin Warmaidens.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "Bijin Wives.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "Northbourne NPCs of Winterhold.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "Bijin NPCs.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Plugin "Northbourne NPCs of Whiterun Hold.esp" appears to be corrupt and cannot be loaded.
[EasyNPC] Beginning mod indexing
[EasyNPC] Finished mod indexing
[EasyNPC] Load order confirmed
[EasyNPC] Creating load order analyzer
[EasyNPC] Beginning load order analysis
[EasyNPC] Starting analysis of "Update.esm"
[EasyNPC] Starting analysis of "Skyrim.esm"
[EasyNPC] Starting analysis of "Dawnguard.esm"
[EasyNPC] Starting analysis of "HearthFires.esm"
[EasyNPC] Starting analysis of "Dragonborn.esm"
[EasyNPC] Completed analysis of "HearthFires.esm"
[EasyNPC] Completed analysis of "Update.esm"
[EasyNPC] Completed analysis of "Dragonborn.esm"
[EasyNPC] Completed analysis of "Dawnguard.esm"
[EasyNPC] Completed analysis of "Skyrim.esm"
[EasyNPC] Analysis completed in 1.01 sec
```

If there's any other information I can provide I'm happy to.
Thank you,
reg1nleifr

**Comment by focustense** [comment]
This looks a lot like a game targeting issue to me. Since that's obviously not the normal install path of the game, does this mean you have multiple instances of the game installed somehow, or aren't using one of the ordinary distributions? If so, use the `-p` or `--game-path` command-line parameter to set the correct game path.

It's also possibly related to multiple Mod Organizer instances, if you use Mod Organizer with named instances. Wabbajack does something (I'm not sure what) to get MO2 to bypass the instance checking, which is the same instance checking that EasyNPC does. If it's an instance problem, then switching your named instance over to a portable instance would update the registry and force EasyNPC to use whichever MO2 directory it happens to be launched from.

But I'd look at the first possibility, first. The "corrupt" messages mean it couldn't read the plugin, which can also happen if MO2 is targeting one game directory and EasyNPC is looking in an entirely different directory.

**Comment by Reg1nleifr** [comment]
By setting up the `--game-path` to point to the Data directory it worked like a charm! Thank you!
