### ISSUE TITLE
Error during startup 

### ISSUE THREAD

**Issue by S-GLITCH-JPG** [focustense/easymod#116]
I get error now after i installed the seranholic valerica plugin and the app refuses to open even when i disabled all of the NPC appearance plugins from my load order 
[Log_20210912_021754_5892941.txt](https://github.com/focustense/easymod/files/7148542/Log_20210912_021754_5892941.txt)

**Comment by focustense** [comment]
Hey, looks like you've been bitten by #103 (corrupted profile). That was due to a bug in v0.9.2, which is fixed in [v0.9.3](https://github.com/focustense/easymod/releases/tag/v0.9.3).

You'll need to fix the profile corruption. I assume you must have exported and re-imported a profile to run into this issue, so the quickest workaround is to just delete the `profile.log` file in `%LocalAppData%\EasyNPC` and let it create a new one for you, then import the saved profile again (in v0.9.3) to restore your settings.

If you want to stay on v0.9.2, you'll have to use the core affinity workaround described in #103. However, if you update to v0.9.3, all you should need to do is delete profile.log and import the saved profile, it won't cause corruption anymore.

I'll be pushing the v0.9.3 update to Nexus soon, so hopefully not many more people run into this. Unfortunately there's no way to prevent it from continuing to happen for those on v0.9.2.

**Comment by focustense** [comment]
Since it's a dupe, I'll be closing. The main difference between right now and what I wrote in #103 is that you can update to v0.9.3 _instead of_ using the core affinity fix, but again, still have to either fix the profile.log or delete it and let the app create a new one. Thanks!
