### ISSUE TITLE
Mugshot support

### ISSUE THREAD

**Issue by TwistedModding** [focustense/easymod#13]
Add mugshot support for:https://www.nexusmods.com/skyrimspecialedition/mods/48904 
and
https://www.nexusmods.com/skyrimspecialedition/mods/48297

The current mugshots for pride of skyrim aio dont seem to work for the version linked above.

**Comment by focustense** [comment]
Pride of Skyrim mugshots definitely work, but you may have it installed under a different name. Did you check the "tip" section in the [Profile guide](https://www.reddit.com/r/skyrimmods/comments/o3igj0/alpha_release_easynpc_how_to_combine_50_overhauls/) about renaming the folder? It has to have the same name as the mod in Mod Organizer (i.e. on your disk).

So for example, if your mod is named "Pride of Skyrim - AIO Male High Poly Head Overhaul" instead of just "Pride of Skyrim - AIO" then you can find the mugshot folder named as the latter and rename it to the former. No need to even restart the app, it'll pick up the changes right away.

FYI, there is actually no magic about the mugshots, they are regular PNG files, and the algo just looks for a mugshot folder with the same name as the mug folder. #3 is also going to support "redirects" for anyone not using the AIO version.

**Comment by TwistedModding** [comment]
Ah yep, renaming the folder/mod worked. Thank you
