### ISSUE TITLE
EasyNPC 0.9.5 Fails To Startup

### ISSUE THREAD

**Issue by Shalecrystal** [focustense/easymod#150]
Hello, and thank you in advance for your time.

I was attempting to run this program, and the first time I launched the application, it loaded successfully, except that it gave the me warning that it couldn't find my mods. (I wasn't loading it through MO2).

Then, after that point: running the app from M02 or running it from anywhere else failed to load at all. I've tried fresh downloads and whatnot, so I was figuring there was something on my pc's end that was stopping it from working, but I have no idea what, I'm not that computer savvy.

Attached should be the log from Event Viewer. Thank you for any help you can provide.

Best Regards!
[EasyNPC Error Report.txt](https://github.com/focustense/easymod/files/8811610/EasyNPC.Error.Report.txt)

**Comment by focustense** [comment]
You're getting the "Could not locate plugins file" error, meaning it can't find `plugins.txt` in the expected location.

Usually this is resolved by running the game once, from the Bethesda launcher - i.e. _not_ from MO2/SKSE/etc. Otherwise, go to `%LocalAppData%\Skyrim Special Edition` - just type that in an explorer window and press enter - and look for a `plugins.txt` file. If you don't see one, then create it, leaving the contents empty.

The above assumes that you're running SE. This particular error can also come up if you're trying to run EasyNPC on different edition of the game from what you've got installed, like if you run VR but didn't configure the app for VR.

**Comment by Shalecrystal** [comment]
I have the plugins.txt doc inside my MO2 INIS folder, which is what I believe I need Easy NPC to find, is there a way I can help that happen?

Yes, sorry, it is SE. I ran the game from the Bethesda launcher and created a plugins.txt file in the Skyrim Special Edition folder, but it didn't seem to help. 
Thank you, regardless!

**Comment by focustense** [comment]
Sorry for the late reply, been pretty busy and I'm sure you've moved on by now.

But in case anyone else runs into this, you need the `plugins.txt` file in `%LocalAppData%\Skyrim Special Edition` (or equivalent for whichever game edition you're running). I'm not sure if this is what you meant by the "Skyrim Special Edition" folder, but it is specifically this folder, and not the game install directory, nor the MO2 INI folder.

This behavior is built into Mutagen, so I can't really do anything about it, although that may change soon due to the GOG release, which seems to put its INIs in a different place and is also broken for Mutagen, Synthesis and related.

If an update comes out to those tools that allows handling different plugin.txt locations, I'll incorporate it. Until then, the workaround is to create an empty text file named `plugins.txt` in the aforementioned location.
