### ISSUE TITLE
Feature Request: change face / default plugin for multiple NPCs

### ISSUE THREAD

**Issue by geraintwd** [focustense/easymod#169]
The NPC Details list on the Build Tab would benefit from the ability to multi-select several NPCs at once (e.g. via the usual Windows CTRL and SHIFT keys), then select a default or face plugin to apply to all of them at once. 

For example, many of the NPCs in my list get Diversity.esp assigned as their Default plugin. I want to be able to change all of them to use Skyrim.esm, or AI Overhaul, for example, since Diversity should only be providing the face.

The current process for this is as follows:

1. Sort NPC Details list by Default plugin column.
2. Scroll down to find the NPCs that have Diversity.esp as their Default plugin.
3. Double click the first NPC, which goes to the Profile tab, with that NPC selected.
4. Click Skyrim.esm
5. Select "Set Default"
6. Return to Build tab
7. Go back to 1 and repeat for the next NPC

The alternative I would suggest would go something like this:

1. Filter NPC Details list by Default plugin column, showing only those NPCs who have Diversity.esp as their Default plugin.
2. Click the first displayed NPC in the filtered list.
3. Scroll to the bottom of the filtered list.
4. Holding down SHIFT, click the last NPC in the list, thus selecting all displayed NPCs.
5. Right-click on any of the highlighted NPCs, to show a context menu.
6. Select "Set default plugin for selected NPCs" from the context menu.
7. Choose preferred plugin from list of valid options (e.g. Skyrim.esm)
8. All selected NPCs will now have Skyrim.esm as their Default plugin, instead of Diversity.esp and they are all done in one pass.

This would ideally work the same way for selecting the face plugin for multiple NPCs, just filter by the appropriate column.

**Comment by focustense** [comment]
Multiple-select will likely not ever be a feature because the semantics just don't work the way they would for e.g. selecting a bunch of files in Explorer. Even though you may have a filtered view in which all NPCs share a particular customizer plugin, they may not share anything else, leading a lot of ambiguous and potentially unresolvable situations, where there's no clear answer for what to display in the plugin list or mugshot lineup, no clear behavior for what happens on single/double-click, etc.

Batch changes in general are a reasonable request, and covered in #72. But the UI won't be a multiple-select in the profile view, it has to be a different kind of view that's purpose-built for that type of workflow.

Incidentally, the "current process" you've listed doesn't make sense to me. You can already filter NPCs by their default plugin in the profile view, so there's no reason to be switching between profile and build tabs for this, and doing so is probably the main issue that's turning a tedious but still pretty quick (maybe a minute or two) process into a slow and error-prone process.

Hopefully I've addressed the immediate pain point with your current process above; since batch changes already have a design, I'm going to dupe the request.

**Comment by geraintwd** [comment]
Ah, OK - I've been doing it wrong! Thanks very much for explaining that, it does help (though there are still a long list of NPCs to go through, now I've filtered the _PROFILE_ screen to show only those that have their default plugin as Diversity.esp.

EDIT: I am a total idiot. I don't even need to do this, as the records in Diversity are the same as those in Skyrim.esm or the USSEP! I've been wasting all this time, mine and yours, and I apologise.
