### ISSUE TITLE
Cant talk/interact with certain NPCs

### ISSUE THREAD

**Issue by arzon94** [focustense/easymod#177]
With an NPC merge enabled, certain NPC's no longer have the 'talk' interaction prompt when alive or viewing their corpse when dead.

Some affected NPCs in Markarth:
- 0009C8AA Weylin
- 0009C8A8 Margret
- 0003F21E Kibell

Nothing appears off in the records for these NPCs as far as I can tell. I have been able replicate with multiple merges, both Modpocalypse and High Poly NPCs produce the issue. Even if an NPC uses the Skyrim.esm as the face source (forwarding default from ussep/ai overhaul) the issue still occurs. The issue happens regardless of enabling de-wigging and disabling all other mods.

**Comment by arzon94** [comment]
I created a merge isolated to only High poly NPC for testing [https://drive.google.com/file/d/1RQneoEyHaDgzMaQCVoBNVQZyZlN3x-_I/view?usp=sharing](https://drive.google.com/file/d/1RQneoEyHaDgzMaQCVoBNVQZyZlN3x-_I/view?usp=sharing)

**Comment by focustense** [comment]
Thanks for the report. As a matter of policy, I don't investigate in-game issues unless accompanied by clear, simple and reasonably fast repro steps or an identification of the specific record/file edits assumed to be responsible.

Since you did include a copy of the merge (really, only the ESP is important), I had a quick look at that in xEdit. I see some obvious anomalies with the NPCs in question. For example, they are all missing names (`FULL` attribute) in the merge. However, this outcome is not repro using the settings you indicated - using USSEP as the default (where available) and High Poly NPC Overhaul as the face. A trial run produced a normal looking ESP with normal names.

What comes out of the merge is a function of what goes in. There is something wrong with your source mods. Please check them more carefully in xEdit. Names are translated strings, so maybe this is a localization issue, e.g. incorrect language settings or missing translation strings for the default. I don't know if the missing name is the sole cause of this issue, but if not the root cause then likely points in the direction of the root cause. You could also test for that by editing one of the NPCs to restore their full name, and see if that fixes the issue.

I may be able to take a closer look if you can provide repro steps. Aside from what I've already mentioned above, the merge/ESP output is not sufficient in this regard because EasyNPC doesn't produce that output under normal circumstances nor any specific exceptional circumstances that I personally know about. I would have to know what's specific to your rig that is responsible for that output, if indeed EasyNPC is responsible and the problems are not already present in the source mod(s). So the repro needs everything: exact steps to set up mod list from a vanilla profile, exact versions of mods installed, exact steps followed in EasyNPC app, etc.

If you can repro the issue starting from a clean game install, then I probably will be able to as well. If not, I will most likely end up tagging this non-repro.

**Comment by arzon94** [comment]
Thanks for the help, after attempting to get repro steps as simple as possible, I Isolated the issue to a mod I never thought would cause the problem. 
No plugin, no npc changes, but [SkyrimVR Strings Files](https://www.nexusmods.com/skyrimspecialedition/mods/16355) actually causes this issue. I never play with localization so I dismissed translated string issues but this mod seems to cause them regardless.
Thanks again for the help, and to any skyrimVR players - may google lead you here.
