### ISSUE TITLE
Build - Apply Face Customizations: immediate error out

### ISSUE THREAD

**Issue by Nicallia** [focustense/easymod#181]
Following several steps until only some mods with form factor 43 remain active as plugin error message. 
Everything else with all facegen data is correct and green.
Proceeding to "build" stage then runs all three previous stages correctly and complete.
Immediately when trying to write facegen data (no progress) the process stops.

[Log_20230320_000401_4939753.txt](https://github.com/focustense/easymod/files/11012643/Log_20230320_000401_4939753.txt)

**Comment by Nicallia** [comment]
Additional Info - I got the following info on the mod responsible for not loading Easy NPC. Disabling this mod makes it work perfectly fine. It's called More Nasty Critters and the response from the mod author on my request is here. (albeit not a very friendly response, I got one very quickly) [here](https://www.loverslab.com/topic/95985-more-nasty-critters-special-edition/page/143/) with reference to bod2 first introduced in Skyrim LE [here](https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/BOD2_Field)

**Comment by focustense** [comment]
He's half right. BOD2 was introduced before SE but only became the default/required subrecord as of SSE/Form 44. Before that, it was BODT, and while the game doesn't seem to care about finding BOD2 on older form versions, it's very rare to find in the wild.

I think Mutagen was at some point [updated to be less rigid about this](https://github.com/Mutagen-Modding/Mutagen/commit/d43fdaf711b77986941f52006507e640101d1fbc), but upgrading the Mutagen package is a hassle and I don't plan to do it for the legacy "LTM" track - sorry. It's already done in the 1.x branches but I have no schedules or estimates on an actual release for those.

Easiest workaround is just disable the mod when running EasyNPC. Since it's a creature mod, not humans or other facegen-enabled races, shouldn't make a difference anyway.

**Comment by Nicallia** [comment]
Thanks so much! Your suggestion is exactly what I did in fact and (in my limited playtest) it worked without a glitch or problem.
