### ISSUE TITLE
EasyNPC doesn't load the plugins!

### ISSUE THREAD

**Issue by Masacroso** [focustense/easymod#186]
Running the program from MO2 and a GOG installation of Skyrim then it just load the masters of the game at the starting screen. After, in profile, I can choose between vanilla and modpocalypse NPCs (that I've installed), however the program says that the modpocalypse plugins were not loaded!

Moreover: I have a list of more than 1700 NPCs and I need to choose one by one to get the modpocalypse version manually???

**Comment by focustense** [comment]
Modpocalypse doesn't _have_ plugins, so you'll always see that message. People generally don't use it as an integral part of a profile, they use it as a "base mod" - because yes, you'd have to select 1700 or however many NPCs manually, but if you're only selecting Modpocalypse for each one then there isn't much of a point in using the app at all.

This topic has been covered in detail quite a number of times in the FAQ ([[Plugin not loaded]](https://github.com/focustense/easymod/wiki/EasyNPC-FAQ-&-Troubleshooting#the-preview-says-plugin-not-loaded-but-it-is-active) and [[Base Mods]](https://github.com/focustense/easymod/wiki/EasyNPC-FAQ-&-Troubleshooting#can-i-use-a-base-mod-for-most-faces-and-customize-a-smaller-number-on-top-of-that)), and about once a week on Discord.

WAI.
