### ISSUE TITLE
Some DLC changes are reverted on the default settings

### ISSUE THREAD

**Issue by ATantalizedLion** [focustense/easymod#19]
![image](https://user-images.githubusercontent.com/47591778/123461787-cab6b580-d5e9-11eb-8f2f-69bc6586ac5d.png)
![image](https://user-images.githubusercontent.com/47591778/123462026-18332280-d5ea-11eb-8b42-bac91e2853e3.png)

This problem seems to mostly (almost exclusively) affect some of the Vampires in the Dawnguard DLC. It looks like the changing of the head part causes the DLC to be labeled as a face mod, overriding the perk, voice, actor effects and faction changes in these NPCs. 

Maybe some logic could be added to check if the mod(or DLC in this case) makes any changes to the NPCs relative to its own masters. Though I am not sure how viable this is performance-wise

**Comment by focustense** [comment]
This is due to a silly bug I accidentally created in 481d8de. It's specifically [this line](https://github.com/focustense/easymod/commit/4a1d8deeaf333991ffa0d198d8394150c36515ba#diff-e6e7fa357ca41d137c101804c858331d060b3b80b618ba8ac1fbdd055887549cR53), where instead of checking the actual name of the default override to see if it's an existing master (very much like the check you're suggesting), it checks an uninitialized variable due to there _not_ being any ITM/ITPOs in the load order.

There's not even any reason for that logic to be there, since the implementation was switched from tracking the plugin name as a separate variable to simply checking that the default override is not null.

I've got a fix tested and will have it pushed soon. Pretty much just reverts that line to the original implementation (with the added null check) which didn't have this bug in the first place.
