### ISSUE TITLE
crash when building

### ISSUE THREAD

**Issue by Piicaro** [focustense/easymod#190]
error seems to be happening with **windhelmhousecarl calder**, i have tried switching him to use every replacer one by one including vanilla

https://pastebin.com/kJw3VVF8

**Comment by focustense** [comment]
Choosing different replacers (faces) isn't likely to help with this issue, because the problem is with the **default** plugin:

```
2023-11-23 15:12:44.132 +05:30 [01] [ERR] Task 'Import NPC Defaults' failed due to an unhandled exception
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'length'))
 ---> RecordException  => HousecarlWindhelm (0A2C90:Skyrim.esm<Npc>): Specified argument was out of the range of valid values. (Parameter 'length') System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Mutagen.Bethesda.Skyrim.Internals.NpcBinaryOverlay.get_NAM5()
   at Mutagen.Bethesda.Skyrim.Internals.NpcSetterTranslationCommon.DeepCopyIn(INpc item, INpcGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
```

This happens during the task "Import NPC Defaults" meaning it has not even gotten to the replacers yet.

Whichever plugin you have specified as the _default_ for `HouseCarlWindhelm` (log doesn't say) has a broken `NAM5` (Name) record. You might be able to check/fix it in xEdit. Otherwise, you'll have to select a different default.

**Comment by Piicaro** [comment]
sorry if this sounds stupid but wouldnt the default plugin for a vanilla npc be skyrim.esm? I tried building with no male replacers and this error still happened

EDIT: Managed to fix it ! It was "**Purist's vanilla patch**"  that was loading as the default and it had nam5 missing. the fix was as simple as editing it and adding FF 00 in it. Hope this helps anyone else encountering this
