### ISSUE TITLE
Kodlak Whitemane I cannot fix

### ISSUE THREAD

**Issue by RyanB1975** [focustense/easymod#200]
This character of course is suffering from the darkface bug. I have the vanilla, and The Men of Winter edition for choices. Yes, I do have the community collection 1, which has The Men of Winter mod. I am able to alter and fix every other NPC in all of the game, this including Interesting NPCs, which had a ton of dark faces until I used Easy NPC.

Default, or the green checkmark choice, neither is working. Both come out dark faced. 

For some reason, it all works, except for with Kodlak.

I've had to reinstall Easy NPC to get it working again. The last time was over a year back. I am not sure if I am missing anything. 

Helpful advice is appreciated!

**Comment by focustense** [comment]
The app hasn't really been updated for a while, so I doubt anything has changed since the last time you used it.

If you're having a problem with a FAQ-covered issue, I suggest first following the recommended troubleshooting steps and then asking on Discord if it's still not solved (including a specific explanation of what you tried, and what you saw in the plugin data, facegen files, etc.).

https://github.com/focustense/easymod/wiki/EasyNPC-FAQ-&-Troubleshooting#npcs-have-black-faces
