### ISSUE TITLE
Build Warning: FaceModMissingFaceGen 

### ISSUE THREAD

**Issue by Oraqle89** [focustense/easymod#52]
So after running the built-in check for problems feature, the Build Warnings were all reporting FaceModMissingFaceGen, the weird thing was that the warnings were all connected to actors that were using seemingly unrelated mods for the face sources. 
e.g: JaySus swords. See the Word Doc attached for the full list.
[EasyNPC Problems.docx](https://github.com/focustense/easymod/files/6849138/EasyNPC.Problems.docx)

So I posted this concern on the Nexus Page, which got a very informative response. I then tried going ahead with the build disregarding the warnings and then got the App Error message and link to Crash Log. 

Please see the attached crash log.

Thank you for the assistance.

[Log_20210720_153606_9196696.txt](https://github.com/focustense/easymod/files/6848892/Log_20210720_153606_9196696.txt)
@focustense

**Comment by focustense** [comment]
Hey there,

You're running an old version of the app. The error that's in the log - which has no relationship to the build warning - was fixed in #31. That's this one:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.File.Delete(String path)
   at Focus.Apps.EasyNpc.Build.BuildViewModel`1.<BeginBuild>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
```

You should be fine if you go grab the newest version.

Regarding the JaySuS warnings, I took a look in `JSwords.esm` and it doesn't modify any NPCs at all, never mind face attributes. It should not even be _possible_ to select that plugin as the face. But it's looking for the mod, not the plugin, which tells me that you've got the face plugin probably set to a patch that's part of JaySuS swords, and that's your problem. Looking at what's in there, maybe it's the Immersive Weapons patch - I think that IW modifies some NPCs, and even modifies some facegens that it ought not to.

Use the filter button (top left) on the Profile page to find out which NPCs have faces pointing to that plugin - whichever one it is - and point them somewhere else if you want. If you don't have any actual customizations for those NPCs that you'd rather use, you can probably just leave them alone and it should be fine. Let's talk about the rest of the errors (if needed) in the discord chat.

Thanks!
