### ISSUE TITLE
Mugshot request: DX's Better Men of Skyrim

### ISSUE THREAD

**Issue by megapatato** [focustense/easymod#58]
DX's Better Men of Skyrim: https://www.nexusmods.com/skyrimspecialedition/mods/18976

Additionally, for overhauls that do not have mugshots yet, would the EasyNPC devs. accept a submission? If so, what format or preparation would be requested? Screenshots of the default head-on view of the FaceGeom files as seen in NifSkope? What resolution?

**Comment by focustense** [comment]
I'm writing a guide on this right now - splitting my time between writing the FAQ and writing the mugshot creation guide. I think you'll find it very tedious and slow to do these in NifSkope without the guide, because most of the mugshots need corrections, and it is hard to take consistent screenshots, and I have a process that will make it easier.

The short answer to your second question would be: yes, I'm happy to add good-quality sets, and the general guidelines would be: front view in NifSkope, square aspect ratio, size is not super important but I'd recommend at least 500x500 (mine are closer to 650x650), PNG format, with some decent textures loaded for mods that don't supply their own (Bijin Skin and Vitruvia are two that I feel are clean but not too plastic-y, but anything that looks both good and semi-realistic is fine).

I'll resume work on mugshots myself when I'm through the really critical bug fixes and features discovered so far.

**Comment by focustense** [comment]
Forgot about this request. Check out the #mugshot-prereleases channel on the Discord, this one's been done.
