### ISSUE TITLE
Something went wrong - Wabbajack Librum Modlist

### ISSUE THREAD

**Issue by MatteoGatto95** [focustense/easymod#67]
I get that message box directly after it tries to initialize my load order. I am trying to modify a deep wabbajack modpack.

[Log_20210723_073427_8241849.txt](https://github.com/focustense/easymod/files/6866764/Log_20210723_073427_8241849.txt)

**Comment by focustense** [comment]
According to the log, it's failing to find an armor (`ARMO`) record that the plugin `The_Sequel.esp` expects to find in `DBM_Patches_Merged`. This is probably referenced as a `WNAM` (Worn Armor, i.e. custom body or wig) by an NPC in `The_Sequel.esp`.

Most likely, this is something like a version conflict or a bad merge. Maybe the merge was done without the dependency in the load order, and therefore the merge changed form IDs and the dependency is no longer valid. Or maybe the plugin was updated after a merge, etc. If `DBM_Patches_Merged` is an official released mod then I'd lean more toward the version of that mod being incompatible with the version of `The_Sequel`.

I'll add a check so that this problem will skip processing and warn on that record instead of crashing. In the meantime, if `The_Sequel.esp` isn't too huge in terms of NPC modifications, you could untick it in the EasyNPC plugin selection screen to get past this error.

**Comment by MatteoGatto95** [comment]
Thank you for the answer! DBM_Patches_Merged and The_Sequel are handmade patches by the very capable Librum modding team. I know they are going to release an update soon, so I'll be checking with that one. By now I'll gladly take the check to avoid the crash and go on with the merge.

Thanks again!
