### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by NairSiddharth** [focustense/easymod#69]
Hey focus, been a while since I've submitted a bug report but I am back! Attached is the necessary log file. The process I was undergoing when this bug appeared was simply loading in all the npc retexture mods that I was using (second screen that pops up, when everything loads in). Any help would be greatly appreciated.
[Log_20210723_152236_0730318.txt](https://github.com/focustense/easymod/files/6871070/Log_20210723_152236_0730318.txt)

**Comment by focustense** [comment]
Is your version current? This looks similar to #53 which is "fixed" (more like worked around) in 0.8.7. Explicit null checks have been added everywhere in that class so these errors can't really happen anymore, at least in that part of the app.

Offhand, I see that the last plugin loading was `PA44_KaidenReplacer1.esp`, and I see a whole bunch of Kaidan-related mods but not the original Kaidan. I'm guessing he must be in a merge somewhere, and the merge changed the form ID, and you installed a new patch/overhaul for him after the merge? That would be my guess. But either way, try it with 0.8.7.

(Mental note - I really need to start putting the version in the log files themselves)

**Comment by NairSiddharth** [comment]
I did not have version 7, had grabbed version six day before yesterday. First update since 0.3 so excited to see all the changes. I do have the Kaidan mod though, esp name is 0Kaidan cause that's what the author put for some reason lol. I'll see if .8.7 fixes it

**Comment by focustense** [comment]
Nope, no `0Kaidan.esp` in the log. Only a `COTN Morthal - Kaidan 2 Patch.esp`, `Great Town of Ivarstead - Kaidan 2 Patch.esp`, and the `PA44_KaidanReplacer1.esp` that's failing.

And EasyNPC won't let you start with missing masters, so in order for those other plugins to even be allowed to load, their master refs must have been changed to something else. That's why I'm guessing a zMerge + ReLinker in here somewhere.

**Comment by NairSiddharth** [comment]
I think I found the cause of the error, needed to put the masters above the npc overhauls (i.e. 0kaidan before the poetic ant kaidan replacer) it worked!

**Comment by focustense** [comment]
Weird that the app let you do that, and that it only failed after the 3rd plugin referencing that mis-ordered master.

The app already has all the logic to perfectly map out all the plugin dependencies in a DCG that supports the loader UI. Guess I never remembered to implement the reordering logic.

Thanks for the report!

**Comment by focustense** [comment]
Even weirder is that I checked, and this case has been explicitly handled since all the way back in v0.3.0. It's already coded to emit a warning similar to "plugin requires master which is not loaded yet".

There must be some other part of the code that can (or could) fail in a similar way. Hope it doesn't trip up too many people in hidden ways now that null checks are all over the place. Just have to close this for now, though.
