### ISSUE TITLE
Head parts and file name issues

### ISSUE THREAD

**Issue by Killing-J0ke** [focustense/easymod#71]
New build doesn't necessarily create new head parts for each modded character so it's ending with lots of master dependencies, which wasn't the main app purpose if I ain't wrong. So I'm basically ending with a patch, but a 2 or three GB one. I even reached 6 GB when I was using High poly NPCs and Diversity (4k encounters is a lot...).
Not sure if it would help but perhaps adding a worn armor removal could help, the same way the app is removing wigs, it could remove worn armor and basically don't care about imbedded skin textures or whatever - at least as an option. This things are using LOTs of space.

App is having a lot of trouble with updated mods with different folder name too, each time I'm updating a mod that changes the folder name (AI overhaul 1.5 to AI Overhaul 1.6 for example, or Vahdin - Female NPC replacer to Vahdin) the whole thing is freaking out and always ends with a crash log. Tbh the whole folder thing is really tedious to manage, would it be possible to simply locate the current plugin location instead of its registered folder ?

**Comment by focustense** [comment]
This is a bit of a mixed bag of questions without a specific bug report, so I'm going to label as that.

> New build doesn't necessarily create new head parts for each modded character so it's ending with lots of master dependencies

[FAQ: My mod has dependencies on the original overhauls](https://github.com/focustense/easymod/blob/master/Focus.Apps.EasyNpc/Docs/faq.md#my-mod-has-dependencies-on-the-original-overhauls-isnt-easynpc-supposed-to-eliminate-those)

I just finished the implementation of #17, which should significantly improve the transparency of that process and make the problems easier to recognize and fix.

> I even reached 6 GB when I was using High poly NPCs and Diversity

Copying and packing the assets is required to make the mod standalone, otherwise this really would just be a "patcher". See above.

> perhaps adding a worn armor removal could help

Worn Armors are not carried over. They are actually going to start to be carried over in #7 - I haven't decided whether to make this opt-in or opt-out yet. However, I doubt it will add much to the total size, since overhaul mods that do use body replacers and wigs generally only define a handful of them. The real reason for removing this customization is to make NPCs compatible with outfits/armors designed for body replacers like CBBE/[BH]UNP.

> App is having a lot of trouble with updated mods with different folder name too

Just heard about this yesterday in a Nexus thread. I assume this must be with Vortex, because the normal process of updating a mod wouldn't cause this behavior in Mod Organizer. In Vortex, the mod metadata is hidden and you can't control when or if it updates and have no control over the mod name either. It's strange that a version bump would trigger this, and if I look at [AI Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/21654) the name is still "AI Overhaul SSE". The file name does have a version, but that is why EasyNPC does selections based on the mod name, _not_ the file name. You shouldn't have "AI Overhaul 1.6" as an actual mod selection option when using the Vortex extension. However, a change to the mod metadata could indeed lead to a broken profile that is entirely beyond the user's control.

In any case, the best resolution is probably going to be #72, and yes, automatically trying to find the new mod name from the old plugin name is going to be a part of that - although it will have certain conditions attached, at least until #4 gets implemented and rollbacks become easier.

Thanks for the feedback, hope this answers all your questions!
