### ISSUE TITLE
Issues finding texture sources

### ISSUE THREAD

**Issue by ryanmccarthy** [focustense/easymod#76]
After a successful build, the log dumps tons of lines saying it couldn't find sources for various textures. This includes things from mod hairs

2021-07-24 23:49:16.902 -04:00 [WRN] Couldn't find a source for file textures\ks hairdo's\gloss_n.dds in any included mods.

to standard assets

2021-07-24 23:49:17.201 -04:00 [WRN] Couldn't find a source for file textures\actors\character\argonianmale\ArgonianMouth.dds in any included mods.

Note that I verified both that the referenced file ("gloss_n.dds" etc) exists and that the mod "KSHairdos" was checked at EasyNPC launch.

**Comment by focustense** [comment]
These aren't necessarily errors, as the log itself should indicate at the bottom. It just means that the mod(s) you're integrating reference assets that are not in those mods themselves, i.e. they have implicit dependencies on assets from another mod, like KS Hairdos.

If you have the mods that contain those assets, and intend to keep them enabled after merge - which is the expected outcome for these "resource mods" - then everything is OK and you won't have any problems in the game with these NPCs. Those lines are written to the log as troubleshooting information, i.e. if you end up with in-game issues due to missing meshes or textures.

It doesn't try to merge assets from your entire load order because that would probably lead to merges of an unreasonable size. Or maybe not - that was my assumption at first, but improvements like #49 may start to revisit this and merge assets from upstream mods. But for the moment, it doesn't do this and so these warnings are normal in a moderately complex build.

**Comment by focustense** [comment]
Should be a non-issue in 0.9+ as resources are now copied from any available mods, and vanilla resources are ignored.
