### ISSUE TITLE
Exception during build due to missing head part (BeastHHBB)

### ISSUE THREAD

**Issue by speedythefirst** [focustense/easymod#83]
[Log_20210806_122501_8065439.txt](https://github.com/focustense/easymod/files/6947140/Log_20210806_122501_8065439.txt)

**Comment by focustense** [comment]
Did you intend to close this right after opening it?

Anyway, the specific error is here:

```
RecordException BeastHHBB.esp => 10A47D:BeastHHBB.esp<HeadPart>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 setup)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.Build(IReadOnlyList`1 npcs, BuildSettings`1 buildSettings, ProgressViewModel progress)
   at Focus.Apps.EasyNpc.Build.BuildViewModel`1.<BeginBuild>b__76_0()
```

I'd have to take a closer look at BeastHHBB, but it appears that some NPCs in BeastHHBB point to a nonexistent head part (that is supposed to be _in_ BeastHHBB), and therefore are broken in general.

There are very few places left in the app where any code assumes that a record will exist, but I guess this is one of them. Even if it ignored the invalid head part reference, it wouldn't result in a useful or stable outcome for that NPC, because it's the original mod that has the problem.

This would be something good to cover in the new analysis engine, it can easily pick out NPCs with invalid form lists and consequently get them blacklisted in the UI. There's no "grayed out" mode for plugins right now where it's possible to see that they exist but know why they can't be used, but it would be a good feature to add.

**Comment by focustense** [comment]
FWIW, I just checked this in my copy of BeastHHBB and the record `10A47D` is actually in there, so I think the original plugin must have been edited in order for this to happen.

I try to make EasyNPC ignore bad refs, but this is one case where I'm reluctant to do it, because failing to import records on build means they _will_ be broken in the game, and there isn't really any way to "back out" the NPC from the patch once the import has started. At least for the near future, these have to continue to be treated as fatal errors.

Can try 0.9.1, I don't know if it will fix it. Also try reinstalling BeastHHBB, and/or removing any mods that might be trying to replace BeastHHBB.esp like a patch for it. Otherwise it's no-repro for me.
