### ISSUE TITLE
Neckseam After Merge

### ISSUE THREAD

**Issue by mckq2ooo** [focustense/easymod#88]
Here is my modlist: [modlist.txt](https://github.com/focustense/easymod/files/6966422/modlist.txt)

Bijin Warmaidens, Wives and NPCs are conflict with Shield Sisters Re-Imagined. I tried many things for solution but it didn't work. Neckseam is going on. Pandorable NPCs, College of Winterhold, Pride of Skyrim mods are working normally but only Bijin and Shield Sisters have problems that neckseam. 

My trials:
1-  I have disable all patches about NPC overhauls (before merge).
2-  I have run Bodyslide
3-  Fixed all problems on "build" tab
4-  Downloaded patches for Bijin, it worked for Bijin but conflicted Shield Sisters and Shield NPCs hairs have turned purple.
5-  I have write setweightnpc commands to console but when changed weight, it turned same as like above.
6-  Open new profile on MO2 and add only USSEP + Bijins + Shield Sisters, same result :(

Images in game:
https://www.hizliresim.com/tdbq1xv (Jenassa from Shield Sisters)
https://www.hizliresim.com/s4zhc13 (Carlotta from Bijin)

Images in Easy NPC:
https://www.hizliresim.com/p8gb0dh
https://www.hizliresim.com/mxwkfh8
https://www.hizliresim.com/c78fa8l
https://www.hizliresim.com/arkh8c8

What I will do??

**Comment by focustense** [comment]
Hey - it's great that you've tried and explained some troubleshooting steps here, although in this case you're pointing to a known issue, that EasyNPC doesn't carry over custom bodies and therefore custom body textures. The work is described in #7.

I'm going to be adding this in the next release, which should fix any issues with Bijin mods.

(I do not recommend the use of prebuilt patches, they tend to cause more problems than they solve when it comes to this tool.)

**Comment by focustense** [comment]
Yes, they work. Body replacers use Worn Armors to change both the body mesh (i.e. type) and textures. The original releases of EasyNPC intentionally ignored these because they cause problems with actual armors - i.e. putting one built for a CBBE BodySlide on an NPC forced into a UNP body type, or vice versa. However, I didn't realize at the time that this decision would result in texture mismatches. My assumption was that the body replacers were only being used to provide geometry, but some of the mod authors used them to change the body texture to match their preferred face tint.

The "correct" way to do this on the mod creation side would have been to use textures consistent with the standard ones used for UNP/CBBE/etc., and then modify skin tone/texture lighting in the records to darken/lighten if they wanted. EasyNPC _does_ forward those records. Anyway, as every modder surely knows, there are plenty of ways to do things in Bethesda modding (and game modding in general) that technically work in isolation but tend to cause compatibility problems.

The short-term fix is not hard, as has already been documented in #7, along with the caveats and longer-term plans.
