### ISSUE TITLE
Crash after attempted build

### ISSUE THREAD

**Issue by Spider4062** [focustense/easymod#92]
Made the changes to the file and attempted to build and got an error before it could be completed. Log file attached. Thank you :)
[Log_20210814_134434_9904333.txt](https://github.com/focustense/easymod/files/6986362/Log_20210814_134434_9904333.txt)

**Comment by focustense** [comment]
Not sure why I missed this, sorry about that.

```
RecordException High Poly Head.esm => 000814:High Poly Head.esm<HeadPart>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 setup)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.Build(IReadOnlyList`1 npcs, BuildSettings`1 buildSettings, ProgressViewModel progress)
   at Focus.Apps.EasyNpc.Build.BuildViewModel`1.<BeginBuild>b__76_0()
```

This indicates that it can't find a record in High Poly Head. Most likely, you are using an HPH-based overhaul with the wrong version of HPH - either using an old version of HPH with a new overhaul, or vice versa.

This has all been rewritten in 0.9.0, so I'm probably not going to be doing much in the way of further investigation. The new release will be going up momentarily, so it might be worth trying that out. If you have issues with 0.9.0 and need to keep using 0.8.8 for a bit, what you should do is look for any plugins you have that uses HPH as a master, and open them up in xEdit. Just the loading messages on their own should tell you where the invalid references are.

**Comment by focustense** [comment]
As of [v0.9.3](https://github.com/focustense/easymod/releases/tag/v0.9.3), there is now a reference checker (#107) which runs on startup and should provide what I hope is very clear guidance on where the errors are. NPC options with invalid references will be disabled in the profile, so they can't be selected and subsequently break the build.

Because this now exists, I'm closing all prior issues related to invalid references. Please report any bugs or other problems you find with the reference checker in a new GitHub issue. Thanks!
