### ISSUE TITLE
Something went wrong bug

### ISSUE THREAD

**Issue by CottonKeemy** [focustense/easymod#93]
first time set up, through vortex. targeted the mod folder, agreed with the mods/load order, bug pops up before it finishes.

[Log_20210815_130729_6213718.txt](https://github.com/focustense/easymod/files/6988532/Log_20210815_130729_6213718.txt)

**Comment by focustense** [comment]
This error message normally comes up when you have an unsorted load order, and specifically when a plugin is listed before one of its masters.

It shouldn't crash EasyNPC, and I thought I fixed the bug a long time ago, but for some reason it persisted through what was supposed to be the fix. Since the loader code has been completely rewritten for the upcoming release, I'm probably not going to address this directly - but I think you can anticipate it being fixed as of 0.9.

**Comment by CottonKeemy** [comment]
i used Loot to sort my load order and it went through just fine so easy work around til the updated version, appreciate the relatively quick reply
