### ISSUE TITLE
Duplicate/"plugin not loaded" mugshot for missing MO2 downloads

### ISSUE THREAD

**Issue by IceLancerSR** [focustense/easymod#99]
Hello!
Is it possible to get more info on mouse over, so i can identify what is plugin suppose to be called when its not recognizing face match to plugin
![plugin](https://user-images.githubusercontent.com/4452102/130363933-26d16cd5-e202-4040-9b18-618bd0d8c1fd.png)

**Comment by focustense** [comment]
EasyNPC can't know what plugin is _supposed_ to be loaded, all it knows is that there's a facegen present in one of your mods but there isn't any plugin active in that mod making record edits.

However, and this is why I renamed the bug, I am 99% positive that this is identical to the issue reported on the Discord a few hours ago, in which deleted/moved/renamed downloads in Mod Organizer are causing the app not to recognize the mod name and produces duplicate tiles in the mugshot section. That was just fixed in 8e0a85488bd40e617069200de6fcf7c09a12e310 and will go out with 0.9.1 - probably within the next hour or two.

If you're a Vortex user, please reopen as it would be a different issue. But if you use MO2, this is happening (temporarily) because EasyNPC needs to find the metadata for the original download, which is unfortunately the only place MO2 actually seems to store this information. The fallback logic just added will use the directory name for the mod name, which is how it behaved prior to 0.9.

**Comment by IceLancerSR** [comment]
Hello
But from what i see, mugshot folder name is identical to my mod folder name
![mug](https://user-images.githubusercontent.com/4452102/130367293-ad59a0fc-03eb-47c1-8d6e-267e2d97e69c.png)

Its also in posted image above It says Mod name SE and below esp its matching preview image of mod name mugshot only it says no plugin loaded

**Comment by focustense** [comment]
Yes, that's why it was treated as a bug and quickly fixed. Prior to 0.9 it would always use the folder name as the mod name, post-0.9 it looks for the mod metadata in the download info. So if the download was deleted or otherwise unavailable, the "obvious" match that used to work was being ignored.

The "plugin not installed" is because it thinks it's seeing two separate mods, which obviously it is not.

**Comment by IceLancerSR** [comment]
Thanks will wait for fix
